SwiftyNames.V1.0/Controllers/NamesCatalogController.cs
using SwiftyNames.V1._0.Models;
using SwiftyNames.V1._0.Persistants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SwiftyNames.V1._0.Controllers
{
    [Authorize]
    public class NamesCatalogController : Controller
    {
        SwiftyNamesEntities context = new SwiftyNamesEntities();
        private Logics logic;
        // GET: NamesCatelog
        public ActionResult CatalogView()
        {
            return View();
        }
        private void BindCombo(NewsPaperModel model, IList<NewsPapersPrice> AvailableNewsPaper)
        {
            List<NewsPapersPrice> importname = new List<NewsPapersPrice>();
            model.NewsPapers = new MultiSelectList(AvailableNewsPaper, "Id", "NewsPaper","Price", importname.Select(x => x.Id));

        }
        [HttpGet]
        public ActionResult AvailableNewsPaper()
        {
             NewsPaperModel model = new NewsPaperModel();
             List<NewsPapersPrice> newspapers = new List<NewsPapersPrice>();
             newspapers = context.NewsPapersPrices.ToList();
             model.PriceList = new MultiSelectList(newspapers, "Id","Price",newspapers.Select(x => x.Id));
             model.NewsPapers = new MultiSelectList(newspapers, "Price", "NewsPaper", newspapers.Select(x => x.Price));
             ViewBag.delievery = "Do you want it delivered to your address";
             return View(model);
        }

        [HttpPost]
        public ActionResult AvailableNewsPaper(NewsPaperModel model)
        {
            
            Delivery deliver = new Delivery();
            if(!string.IsNullOrEmpty(model.Address) && !string.IsNullOrEmpty(model.phoneNumber))
            {
                deliver.Address = model.Address;
                deliver.PhoneNumber = model.phoneNumber;
                deliver.DateOrdered = DateTime.Now;
                context.Deliveries.Add(deliver);
                context.SaveChanges();
                TempData["success"] = "Your NewsPaper will be delivered to the given address in three days you can now proceed to payment";
            }

            List<NewsPapersPrice> newspapers = new List<NewsPapersPrice>();
            newspapers = context.NewsPapersPrices.ToList();
            model.PriceList = new MultiSelectList(newspapers, "Id", "Price", newspapers.Select(x => x.Id));
            model.NewsPapers = new MultiSelectList(newspapers, "Price", "NewsPaper", newspapers.Select(x => x.Price));
            ViewBag.delievery = "Do you want it delivered to your address";
            model.phoneNumber = string.Empty;
            model.Address = string.Empty;

            return View(model);
        }



        public ActionResult ChangeOfNamey()
        {
            return View();
        }
        public ActionResult ChangeOfNameForm()
        {
            return View();
        }
    }
}

SwiftyNames.V1.0/Views/NamesCatalog/AvailableNewsPaper.cshtml
@model SwiftyNames.V1._0.Models.NewsPaperModel
@{
    
    ViewBag.Title = "AvailableNewsPaper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["Success"];
        </div>
    }
</div>
    <h3 class="col-lg-offset-1">Available News Paper</h3>
    <div class="col-lg-12">
        <div id="listbox" class="text-primary col-lg-offset-1" style="height:400px;">

            <table class="table table-condensed text-justify text-uppercase style=" border:none">
                <tr class="text-justify text-primary">
                    <td>NEWS PAPERS</td>
                    <td>PRICE</td>
                </tr>
            </table>
            <hr />
            <div>
                @foreach (var item in Model.NewsPapers)
                {
                    var insertme = item.Selected ? "checked=\"checked\"" : @String.Empty;
                    var forname = "for=\"group" + @item.Value + "\"";
                    var idName = "id=\"group" + @item.Value + "\"";

                    <ul class="list-unstyled">
                        <li style="font-size:large">

                            <label class="checkbox" @forname>
                                <input id="checker" type="checkbox" name="groups" value="@item.Value"
                                       @idName @insertme />
                                @item.Text
                            </label>
                        </li>
                    </ul>
                }
            </div>
            <div class="col-lg-offset-8" style="margin-top:-15em">

                @foreach (var item in Model.PriceList)
                {
                    var insertme = item.Selected ? "checked=\"checked\"" : @String.Empty;
                    var forname = "for=\"group" + @item.Value + "\"";
                    var idName = "id=\"group" + @item.Value + "\"";
                    <ul class="list-unstyled">
                        <li style="list-style: none; font-size:large">
                            <label @forname>
                                &#x20a6 @item.Text
                            </label>
                        </li>
                    </ul>
                }
            </div>

            <div class="text-success col-lg-offset-8" style="font-size:medium">Total Amount</div>
            <div class="text-capitalize col-lg-offset-8" id="price" style="border:solid 1px;height:28px;width:275px;font-size:large"></div>

            <input class="btn btn-success btn-block col-lg-offset-8" type="button" style="margin-top:5px" value="PROCEED TO PAYMENT" />
            <div style="margin-top:-6.5em">
                <label>Do you want it to be delivered to your address?</label>
                <div class="checkbox">
                    <label class="checkbox-label">YES</label><input type="checkbox" id="yes" value="500" data-toggl />
                </div>

                <div>
                    <input type="checkbox" id="no" value="0" /><label class="checkbox-label">NO</label>
                </div>
            </div>

            <br />
            <div id="form">
                @using (Ajax.BeginForm("AvailableNewsPaper", "NamesCatalog", new AjaxOptions { HttpMethod = "post" }))
                {
                    <div>
                        @Html.LabelFor(x => x.phoneNumber, new { })
                        @Html.TextBoxFor(x => x.phoneNumber, new { @class = "form-control" })

                    </div>
                    <div>
                        @Html.LabelFor(x => x.Address, new { })
                        @Html.TextAreaFor(x => x.Address, new { @class = "form-control" })
                    </div>
                    <div>
                        <br />
                        <input type="submit" value="Submit" class="btn btn-primary btn-block form-control" />
                    </div>
                }
            </div>
        </div>

    </div>
    <script>
        $(document).ready(function () {
            $("input:checkbox:checked").attr("checked", false);
            $("form").hide();
        });
        jQuery("input[type=checkbox]").click(function () {
            var totali = 0;
            jQuery("input[type=checkbox]:checked").each(function () {


                totali += parseFloat(jQuery(this).val());

            });

            jQuery('#price').html(totali + '&#x20a6');
            //$("#yes").click(function () {
            //    if (this.checked) {

            //        totali += parseFloat(jQuery(this).val());
            //        $('#no').prop('checked', false);
            //        $("form").show();
            //    }
            //});

            $("#no").click(function () {
                if (this.checked) {
                    totali += parseFloat(jQuery(this).val());
                    $('#yes').prop('checked', false);
                    $("form").hide();
                }

            });
        });


        $("#yes").click(function () {
            if (this.checked) {
                $('#no').prop('checked', false);
                $("form").show();
            }
        });




    </script>

SwiftyNames.V1.0/Views/NamesCatalog/CatalogView.cshtml
@model SwiftyNames.V1._0.Models.NewsPaperModel
@{
    ViewBag.Title = "CatalogView";
}

<h2>CatalogView</h2>
@Html.ActionLink("Click to have Your name Change", "AvailableNewsPaper", "NamesCatalog")
<br/>
<hr/>
Metro Style


<div>

 
        @*@foreach (var list in ViewData["batch"] as List<SelectListItem>)
            {
                var e = new List<string>();
                <li style="display: block;height:15px;">@Html.CheckBox(list.Value)</li>
                <li style="display: block; height: 15px; font-size: 12px;margin-left:25px;margin-top:-15px">@Html.Label(list.Text)</li>
                e.Add(list.Selected.ToString());
               TempData["r"] = e;

            }*@

   
</div>

SwiftyNames.V1.0/Views/NamesCatalog/ChangeOfNameForm.cshtml
@model SwiftyNames.V1._0.Models.NameChanger
@{
    ViewBag.Title = "ChangeOfNameForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChangeOfNameForm</h2>

<div class="container" id="myWizard">

    <h3>Bootstrap Wizard</h3>

    <hr>

    <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="5" style="width: 20%;">
            Step 1 of 5
        </div>
    </div>

    <div class="navbar">
        <div class="navbar-inner">
            <ul class="nav nav-pills">
                <li class="active"><a href="#step1" data-toggle="tab" data-step="1">Step 1</a></li>
                <li><a href="#step2" data-toggle="tab" data-step="2">Step 2</a></li>
                <li><a href="#step3" data-toggle="tab" data-step="3">Step 3</a></li>
                <li><a href="#step4" data-toggle="tab" data-step="4">Step 4</a></li>
                <li><a href="#step5" data-toggle="tab" data-step="5">Step 5</a></li>
            </ul>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="step1">

            <div class="well">

                <label>Security Question 1</label>
                <select class="form-control input-lg">
                    <option value="What was the name of your first pet?">What was the name of your first pet?</option>
                    <option value="Where did you first attend school?">Where did you first attend school?</option>
                    <option value="What is your mother's maiden name?">What is your mother's maiden name?</option>
                    <option value="What is your favorite car model?">What is your favorite car model?</option>
                </select>
                <br>
                <label>Enter Response</label>
                <input class="form-control input-lg">

            </div>

            <a class="btn btn-default btn-lg next" href="#">Continue</a>
        </div>
        <div class="tab-pane fade" id="step2">
            <div class="well">

                <label>Security Question 2</label>
                <select class="form-control  input-lg">
                    <option value="What was the name of your first pet?">What was the name of your first pet?</option>
                    <option selected="" value="Where did you first attend school?">Where did you first attend school?</option>
                    <option value="What is your mother's maiden name?">What is your mother's maiden name?</option>
                    <option value="What is your favorite car model?">What is your favorite car model?</option>
                </select>
                <br>
                <label>Enter Response</label>
                <input class="form-control  input-lg">

            </div>
            <a class="btn btn-default next" href="#">Continue</a>
        </div>
        <div class="tab-pane fade" id="step3">
            <div class="well"> <h2>Step 3</h2> Add another step here..</div>
            <a class="btn btn-default next" href="#">Continue</a>
        </div>
        <div class="tab-pane fade" id="step4">
            <div class="well"> <h2>Step 4</h2> Add another almost done step here..</div>
            <a class="btn btn-default next" href="#">Continue</a>
        </div>
        <div class="tab-pane fade" id="step5">
            <div class="well"> <h2>Step 5</h2> You're Done!</div>
            <a class="btn btn-success first" href="#">Start over</a>
        </div>
    </div>

    <hr>

    <a href="http://www.bootply.com/wj9gWh8ulj">Edit on Bootply</a>

    <hr>

</div>



@*<div id="rootwizard">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <ul>
                    <li><a href="#tab1" data-toggle="tab">First</a></li>
                    <li><a href="#tab2" data-toggle="tab">Second</a></li>
                    <li><a href="#tab3" data-toggle="tab">Third</a></li>
                    <li><a href="#tab4" data-toggle="tab">Forth</a></li>
                    <li><a href="#tab5" data-toggle="tab">Fifth</a></li>
                    <li><a href="#tab6" data-toggle="tab">Sixth</a></li>
                    <li><a href="#tab7" data-toggle="tab">Seventh</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="tab-content">
        <div class="tab-pane" id="tab1">
            1
        </div>
        <div class="tab-pane" id="tab2">
            2
        </div>
        <div class="tab-pane" id="tab3">
            3
        </div>
        <div class="tab-pane" id="tab4">
            4
        </div>
        <div class="tab-pane" id="tab5">
            5
        </div>
        <div class="tab-pane" id="tab6">
            6
        </div>
        <div class="tab-pane" id="tab7">
            7
        </div>
        <ul class="pager wizard">
            <li class="previous first" style="display:none;"><a href="#">First</a></li>
            <li class="previous"><a href="#">Previous</a></li>
            <li class="next last" style="display:none;"><a href="#">Last</a></li>
            <li class="next"><a href="#">Next</a></li>
        </ul>
    </div>
</div>*@





<script>


    //$(document).ready(function () {
    //    $('#rootwizard').bootstrapWizard();
    //})

$('.next').click(function(){

  var nextId = $(this).parents('.tab-pane').next().attr("id");
  $('[href=#'+nextId+']').tab('show');
  return false;

})

$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {

  //update progress
  var step = $(e.target).data('step');
  var percent = (parseInt(step) / 5) * 100;

  $('.progress-bar').css({width: percent + '%'});
  $('.progress-bar').text("Step " + step + " of 5");

  //e.relatedTarget // previous tab

})

$('.first').click(function(){

  $('#myWizard a:first').tab('show')

})
</script>

SwiftyNames.V1.0/Views/NamesCatalog/ChangeOfNamey.cshtml
@{
    ViewBag.Title = "ChangeOfNamey";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChangeOfNamey</h2>
<html>
@*<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js"></script>
</head>*@
<body>
    <form method="POST" class="form" action="">
        <div class="step">Window 1</div>
        <div class="step">Window 2</div>
        <div class="step">Window 3</div>
        <div class="step">Window 4</div>
        <button type="button" class="action back">Back</button>
        <button type="button" class="action next">Next</button>
        <button type="button" class="action submit">Submit</button>
    </form>
</body>
</html>
<script>
$(document).ready(function(){
	var current = 1;

	widget      = $(".step");
	btnnext     = $(".next");
	btnback     = $(".back");
	btnsubmit   = $(".submit");

	// Init buttons and UI
	widget.not(':eq(0)').hide();
	hideButtons(current);
	setProgress(current);

	// Next button click action
	btnnext.click(function(){
		if(current < widget.length){
			// Check validation
			if($(".form").valid()){
				widget.show();
				widget.not(':eq('+(current++)+')').hide();
				setProgress(current);
			}
		}
		hideButtons(current);
	})

	// Back button click action
	btnback.click(function(){
		if(current > 1){
			current = current - 2;
			if(current < widget.length){
				widget.show();
				widget.not(':eq('+(current++)+')').hide();
				setProgress(current);
			}
		}
		hideButtons(current);
	})

	// Submit button click
	btnsubmit.click(function(){
		alert("Submit button clicked");
	});

    $('.form').validate({ // initialize plugin
		ignore:":not(:visible)",
		rules: {
			name : "required"
		},
    });

});

// Change progress bar action
setProgress = function(currstep){
	var percent = parseFloat(100 / widget.length) * currstep;
	percent = percent.toFixed();
	$(".progress-bar").css("width",percent+"%").html(percent+"%");
}

// Hide buttons according to the current step
hideButtons = function(current){
	var limit = parseInt(widget.length);

	$(".action").hide();

	if(current < limit) btnnext.show();
	if(current > 1) btnback.show();
	if (current == limit) {
		btnnext.hide();
		btnsubmit.show();
	}
}
</script>